### ISSUE TITLE
Game fails to load due to missing font

### ISSUE THREAD

**Issue by Draluy** [imiolek-ireneusz/eduActiv8#42]
Hi, when using the last master commit, I have the following error when launching the game:

    ` python3 eduactiv8.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Using fribidi library.
eduActiv8: You may like to install eSpeak to get some extra functionality, however this is not required to successfully use the game.
Traceback (most recent call last):
  File "eduactiv8.py", line 690, in <module>
    main()
  File "eduactiv8.py", line 680, in main
    app.run()
  File "eduactiv8.py", line 474, in run
    self.game_board = self.game_const(self, self.speaker, self.config, self.size[0], self.size[1])
  File "/media/lymphocyte/projets/eduActiv8/game_boards/game000.py", line 14, in __init__
    gd.BoardGame.__init__(self, mainloop, speaker, config, screen_w, screen_h, 25, 16)
  File "/media/lymphocyte/projets/eduActiv8/classes/game_driver.py", line 83, in __init__
    self.board = classes.board.Board(self.mainloop, 3, 3, 50)
  File "/media/lymphocyte/projets/eduActiv8/classes/board.py", line 1018, in __init__
    self.level_start(x_count, y_count, scale)
  File "/media/lymphocyte/projets/eduActiv8/classes/board.py", line 1131, in level_start
    self.font_sizes_lng["ml_1.75"] = pygame.font.Font(self.font_ml, (int(float(self.points) / 1.75)))
FileNotFoundError: [Errno 2] No such file or directory: 'res/fonts/Noto/NotoSerifMalayalam-Regular.ttf'
`

This is not the case on the branch from my PR #41 , so I gues somethin happened in the last 3 commits.

**Comment by imiolek-ireneusz** [comment]
Thanks for pointing this out. 
Looks like I forgot to `add` a font file for a language that was requested, but not translated. The language itself is 'hidden', but I forgot to add and commit the file or comment out the references to the font file. I'll get it fixed as soon  as I can.
